// This file is auto-generated by @hey-api/openapi-ts

export const fileSchema = {
	type: 'string'
} as const

export const fileResponceSchema = {
	type: 'object',
	properties: {
		item: {
			type: 'object',
			properties: {
				expiration_date_type: {
					type: 'string'
				},
				last_name_type: {
					type: 'string'
				},
				document_number: {
					type: 'string'
				},
				document_number_type: {
					type: 'string'
				},
				last_name: {
					type: 'string'
				},
				document_number_confidence: {
					type: 'number'
				},
				first_name: {
					type: 'string'
				},
				first_name_type: {
					type: 'string'
				},
				input: {
					type: 'string'
				},
				first_name_confidence: {
					type: 'number'
				},
				expiration_date: {
					type: 'string'
				},
				last_name_confidence: {
					type: 'number'
				},
				expiration_date_confidence: {
					type: 'number'
				}
			}
		},
		file: {
			type: 'object',
			properties: {
				identity: {
					type: 'object',
					properties: {
						FIRST_NAME: {
							type: 'object',
							properties: {
								text: {
									type: 'string'
								},
								type: {
									type: 'string'
								},
								confidence: {
									type: 'number'
								}
							}
						},
						LAST_NAME: {
							type: 'object',
							properties: {
								text: {
									type: 'string'
								},
								type: {
									type: 'string'
								},
								confidence: {
									type: 'number'
								}
							}
						},
						DOCUMENT_NUMBER: {
							type: 'object',
							properties: {
								text: {
									type: 'string'
								},
								type: {
									type: 'string'
								},
								confidence: {
									type: 'number'
								}
							}
						},
						EXPIRATION_DATE: {
							type: 'object',
							properties: {
								text: {
									type: 'string'
								},
								type: {
									type: 'string'
								},
								confidence: {
									type: 'number'
								}
							}
						}
					}
				}
			}
		}
	}
} as const

export const ErrorResponseSchema = {
	type: 'object',
	properties: {
		message: {
			type: 'string',
			description: 'A message describing the error.'
		}
	}
} as const

export const DocumentResponseSchema = {
	type: 'object',
	description: 'Document object.',
	properties: {
		id: {
			type: 'integer',
			description: 'Document unique identifier.'
		}
	}
} as const
