// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'
import type {
	SlsTextractOcrDevGetDocumentByFileNameData,
	SlsTextractOcrDevGetDocumentByFileNameError,
	SlsTextractOcrDevGetDocumentByFileNameResponse
} from './types.gen'

export const client = createClient(createConfig())

/**
 * /patent/{file}
 * Get the patent by the file name if exist
 */
export const slsTextractOcrDevGetDocumentByFileName = <ThrowOnError extends boolean = false>(
	options: Options<SlsTextractOcrDevGetDocumentByFileNameData, ThrowOnError>
) => {
	return (options?.client ?? client).get<
		SlsTextractOcrDevGetDocumentByFileNameResponse,
		SlsTextractOcrDevGetDocumentByFileNameError,
		ThrowOnError
	>({
		...options,
		url: '/patent/{file}'
	})
}
