// This file is auto-generated by @hey-api/openapi-ts

/**
 * Document object.
 */
export type DocumentResponse = {
	/**
	 * Document unique identifier.
	 */
	id?: number
}

export type ErrorResponse = {
	/**
	 * A message describing the error.
	 */
	message?: string
}

export type file = string

export type fileResponce = {
	expiration_date_type?: string
	last_name_type?: string
	document_number?: string
	document_number_type?: string
	last_name?: string
	document_number_confidence?: number
	first_name?: string
	first_name_type?: string
	input?: string
	first_name_confidence?: number
	expiration_date?: string
	last_name_confidence?: number
	expiration_date_confidence?: number
	item?: {
		expiration_date_type?: string
		last_name_type?: string
		document_number?: string
		document_number_type?: string
		last_name?: string
		document_number_confidence?: number
		first_name?: string
		first_name_type?: string
		input?: string
		first_name_confidence?: number
		expiration_date?: string
		last_name_confidence?: number
		expiration_date_confidence?: number
	}
	file?: {
		identity?: {
			FIRST_NAME?: {
				text?: string
				type?: string
				confidence?: number
			}
			LAST_NAME?: {
				text?: string
				type?: string
				confidence?: number
			}
			DOCUMENT_NUMBER?: {
				text?: string
				type?: string
				confidence?: number
			}
			EXPIRATION_DATE?: {
				text?: string
				type?: string
				confidence?: number
			}
		}
	}
}

export type SlsTextractOcrDevGetDocumentByFileNameData = {
	path: {
		/**
		 * file name that was uploaded
		 */
		file: file
	}
}

export type SlsTextractOcrDevGetDocumentByFileNameResponse = fileResponce

export type SlsTextractOcrDevGetDocumentByFileNameError = DocumentResponse | ErrorResponse
